# Generated by Django 4.2.26 on 2025-11-07 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "publish_date",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("detail_link", models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
